import "./globals.css";
import type { Metadata } from "next";
import {Noto_Sans_JP} from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import Link from "next/link"

const zenKaku = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "kei5ot.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={notoSansJP.className}
          style={{ zoom: "80%",}
        }
      >
        {children}
        <div style={{ marginTop: 80, textAlign: "center", paddingBottom: 100 }}>
          <p style={{ opacity: 0.5, fontSize: 14 }}>Created by [kei5o55]</p>
          <div style={{ display: "flex", justifyContent: "center", gap: 20, marginTop: 10 }}>
              <Link href="/">Home</Link>
          </div>
        </div>
      </body>
        
      
    </html>
  );
}
