import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Sans_JP, DotGothic16 } from "next/font/google";

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans",
});
const myCustomFont = localFont({
  src: "../public/fonts/wapuro-mincho.otf", // publicからの相対パス
  variable: "--font-my-custom",
  display: "swap",
});

const dotGothic = DotGothic16({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dot-gothic",
});

export const metadata: Metadata = {
  title: "kei5ot.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${notoSansJP.variable} ${dotGothic.variable} ${myCustomFont.variable}`}>
      <body style={{ zoom: "100%" }}>
        {children}
      </body>
    </html>
  );
}